# Generated by Django 5.2.1 on 2025-05-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField()),
                ('row_count', models.IntegerField()),
                ('column_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ColumnMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('original_type', models.CharField(max_length=100)),
                ('inferred_type', models.CharField(max_length=100)),
                ('applied_type', models.CharField(blank=True, max_length=100, null=True)),
                ('null_count', models.IntegerField()),
                ('unique_count', models.IntegerField()),
                ('processed_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='data_inference.processedfile')),
            ],
        ),
    ]
